stages:
    - test
    - staging
    - deploy

before_script:
    - cd Code/api

test_api:
    stage: test
    image: python:latest
    script:
        - apt-get -y update && apt-get -y install postgresql 
        - python3 -m venv venv
        - . venv/bin/activate
        - pip install -r requirements.txt
        - pip install -r requirements-dev.txt
        - su -c 'coverage run -m pytest' postgres
        - coverage report
    # only:
    #     - branches
    #     - merge_requests

staging_api_container:
    stage: staging
    image: mcr.microsoft.com/azure-cli
    script:
        - az login --service-principal -u $SP_APP_ID -p $SP_PASSWORD --tenant $SP_TENANT
        - az acr build --registry collegetalk --image collegetalk-api-staging .
    only:
        refs:
            # - merge_requests
            - main

deploy_api_container:
    stage: deploy
    image: mcr.microsoft.com/azure-cli
    script:
        - az login --service-principal -u $SP_APP_ID -p $SP_PASSWORD --tenant $SP_TENANT
        - az acr build --registry collegetalk --image collegetalk-api .
    only:
        - main
