version: "3.8"

services:
  api:
    container_name: collegetalk-api
    restart: always
    build: 
      context: ./api 
      dockerfile: Dockerfile-dev
    environment:
      - FLASK_ENV=docker
    volumes:
      - ./api:/api
    ports:
      - "9000:9000"
    depends_on:
      - database
    entrypoint: 
      - /api/scripts/docker_script.sh
  
  database:
    image: postgres:latest
    container_name: collegetalk-database
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - app-db:/var/lib/postgresql/data

volumes:
  app-db:
    name: app-db

    