version: "3.8"
services:
  api:
    restart: always
    container_name: api
    build: ./api
    expose:
      - 5000
    ports:
      - "5000:5000"
    volumes:
      - ./api:/usr/src/app
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
      - FLASK_DEBUG=1
