stages:
    - lint
    - test
    - staging
    - deploy

image: node:alpine

before_script:
    - cd Code/frontend
    - npm install

lint_frontend:
    stage: lint
    script:
        - npm ci
        - npm run lint
    only:
        - branches
        - merge_requests

test_frontend:
    stage: test
    needs: [lint_frontend]
    script:
        - npm ci
        - npx jest --ci
    only:
        - branches
        - merge_requests

staging_frontend_expo:
    stage: staging
    needs: [test_frontend]
    script:
        - cd Code/frontend
        - npm install
        - npm install expo-cli
        - apk add --no-cache bash
        - npx expo publish --non-interactive
    only:
        - main
        - merge_requests

deploy_frontend:
    stage: deploy
    needs: [staging_frontend_expo]
    script:
        - echo "Deploying frontend"
    only:
        - main
