stages:
    - lint
    - test
    - staging
    - deploy

image: node:alpine

before_script:
    - npm install

lint_frontend:
    stage: lint
    script:
        - npm ci
        - npm run lint
    rules:
        - if: $CI_PIPELINE_SOURCE == "merge_request_event" || $CI_PIPELINE_SOURCE == "push"

test_frontend:
    stage: test
    needs: [lint_frontend]
    script:
        - npm ci
        - npx jest --ci
    rules:
        - if: $CI_PIPELINE_SOURCE == "merge_request_event" || $CI_PIPELINE_SOURCE == "push"

staging_frontend_expo:
    stage: staging
    needs: [test_frontend]
    script:
        - cd Code/frontend
        - npm install
        - npm install expo-cli
        - apk add --no-cache bash
        - npx expo publish --non-interactive
    rules:
        - if: $CI_PIPELINE_SOURCE == "merge_request_event" || $CI_COMMIT_BRANCH == "main"

deploy_frontend:
    stage: deploy
    needs: [staging_frontend_expo]
    script:
        - echo "Deploying frontend"
    only:
        - main
